### ISSUE TITLE
Refactor  all documentations

### ISSUE THREAD

**Issue by maslow** [labring/laf-roadmap#14]
## Summary

👉  key points: 
- i18n support (at least for zh & en)
- intro
- quick start
- tutorial for examples
- client: cli user guide
- client: web user guide
- db guide
- function guide
- oss guide
- api references: crd, kube api
- architecture
- contribution guide
- deployment guide
- documentation hits
- posts & links

## Intended Outcome

- Determine documentation categories
- Determine project plan and structure

**Comment by sulnong** [comment]
> @sulnong accepted at 2/6/2023

Every doc releated `quesitons` or `advice` could list under this issue.

**Comment by sulnong** [comment]
## Initial plan with time node:
- `2.8`: Cloud Funcs
- `2.9`: Cloud Database
- `2.10` : Cloud storage & Static hosting (need help @maslow )
- `2.11`:  relax
- `2.12`:  laf-cli & private deployment（laf-cli documents could provided by author）
- `2.13`-`2.15`: supplemented additional **practice user case** & re-check & some chore jobs
