### ISSUE TITLE
Design and implement laf cli

### ISSUE THREAD

**Issue by maslow** [labring/laf-roadmap#9]
# cli设计与实现

# 技术选型

暂定commander.jshttps://github.com/tj/commander.js/

# 功能模块

- 用户认证
- 应用管理
- 云函数
- 对象存储
- 静态网站

# 目录设计

这应该是nodejs目录设计，其他的可能存在不同

- laf.json
- functions
    - function_name
        - index.ts
        - meta.json
    - package.json

# 命令设计

### 登录

```bash
laf login -u usernaem -p password
```

### 登出

```bash
laf logout
```

### 应用列表

```bash
laf list app [OPTIONS]
```

| 参数 | 作用 |
| --- | --- |
| -f | 过滤应用名称 |

### 启动应用

```bash
laf start app [APP_ID]
```

### 关闭应用

```bash
laf stop app [APP_ID]
```

### 重启应用

```bash
laf restart app [APP_ID]
```

### 初始化目录

```bash
laf init app [APP_ID]
```

### 函数列表

```bash
laf list func [OPTIONS]
```

| 参数 | 作用 |
| --- | --- |
| -f | 过滤函数名称 |

### 拉取函数

```bash
laf pull func -A # 拉取所有函数
laf pull func [FUNCTION_NAME] # 拉取指定函数
```

**可能存在覆盖本地代码**

### 部署函数

```bash
laf deploy func -A # 部署所有函数
laf deploy func [FUNCTION_NAME] # 部署指定函数
```

### 桶列表

```bash
laf list storage [OPTIONS]
```

| 参数 | 作用 |
| --- | --- |
| -f | 过滤应用名称 |

### 创建桶

```bash
laf create storage [BUCKET_NAME]
```

### 删除桶

```bash
laf del storage [BUCKET_NAME] [OPTIONS]
```

| 参数 | 作用 |
| --- | --- |
| -f | 强制删除（桶非空） |

### 推送文件

```bash
laf push [SOURCE_DIR][BUCKET_NAME] [OPTIONS]
```

| 参数 | 作用 |
| --- | --- |
| -r | 桶内目录 |
| -f | 如果桶内存在相同文件，则强制覆盖 |

### 拉取文件

```bash
laf pull [BUCKET_NAME] [DIST_DIR] [OPTIONS]
```

| 参数 | 作用 |
| --- | --- |
| -r | 桶内目录 |
| -f | 如果本地存在相同文件，则强制覆盖 |

### 创建静态网站

```bash
laf create website [NAME] [BUCKET_NAME]
```

### 部署静态网站

```bash
laf deploy website [SOURCE_DIR] [WEBSITE_NAME]
```

### 拉取静态网站

```bash
laf pull website [WEBSITE_NAME] [DIST_DIR]
```

### 删除静态网站

```bash
laf del website [WEBSITE_NAME]
```

# 存在问题

## 本地编写函数提示问题如何解决？
TODO

# 可参考文档

[https://sunbk201.github.io/cli-guidelines-zh/](https://sunbk201.github.io/cli-guidelines-zh/)

**Comment by maslow** [comment]
目录结构，我打算把每个函数的外层的文件夹去除，这样更简洁一些。和实际路径径保持一致性，同时 vscode 提示也就更好做了，多套一层目录很多地方不好处理，除了 vscode 提示、在线IDE 提示要特殊处理外， import 其它函数 也会麻烦些。

Sample 1:

- .laf.json
- @laf/
  - functions/
    - index.ts
    - login.ts
    - register.ts
  - policies/
  - triggers/
  - others in future
  - app.json

Sample 2:

- .laf.yaml
- cloud/
  - app.json
  - functions/
    - index.ts
    - index.meta.yaml
    - login.ts
    - login.meta.yaml
    - register.ts
    - register.meta.yaml
    - ...
  - policies/
     - app.json
     - admin.json
     - ...
  - triggers/
    - timer_1min.yaml
    - files_add_for_convert_png.yaml
    - app_ready.yaml
    - websocket.yaml
    - ...
  - (other directory in future)

**Comment by skyoct** [comment]
1. 平铺开是简洁很多
2. 除了package.json其他是否能够全部使用yaml格式文件

**Comment by maslow** [comment]
> 1. 平铺开是简洁很多
> 2. 除了package.json其他是否能够全部使用yaml格式文件

我觉得可以，都用 yaml
