### ISSUE TITLE
修改应用信息报错

### ISSUE THREAD

**Issue by LeezQ** [labring/laf-roadmap#96]
![Image](https://user-images.githubusercontent.com/972813/216827415-20c61a41-4a00-4ed7-9be6-01bc31ed7ad1.png)

**Comment by kongwy229** [comment]
feat(web): fix home page & function page bugs ([#735](https://github.com/labring/laf/pull/735))
fix(web): fix app info edit bug ([#738](https://github.com/labring/laf/pull/738))
web/src/pages/home/mods/CreateAppModal/index.tsx
